# Generated by Django 3.2.7 on 2021-09-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0007_productvariation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariation',
            new_name='Variation',
        ),
    ]
