# Generated by Django 3.2.7 on 2021-09-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0008_rename_productvariation_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='frontpage.Variation'),
        ),
    ]
