# Generated by Django 3.2.7 on 2021-09-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0009_cartitem_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variation',
            new_name='variations',
        ),
    ]
