# Generated by Django 3.2.7 on 2021-09-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0010_rename_variation_cartitem_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(to='frontpage.Variation'),
        ),
    ]
