# Generated by Django 3.2.7 on 2021-09-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0012_auto_20210916_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='frontpage.Variation'),
        ),
    ]
