# Generated by Django 3.2.7 on 2021-09-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210920_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
